langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: devstral
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: devstral

github:
  token: <paste github token here>

